### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by Yohannfra** [alcover/stricks#1]
Hi,

I tried to clone it and compile it but it directly fails, any idea ?

I'm on mac so it compiles with clang.

```
clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
<img width="816" alt="Capture d’écran 2021-03-11 à 23 11 32" src="https://user-images.githubusercontent.com/36271388/110863076-697c0800-82c0-11eb-8548-82f37dcec747.png">

**Comment by Yohannfra** [comment]
ok after a quick look at the makefile I just had to create the bin directory with

```
mkdir bin
```

**Comment by Yohannfra** [comment]
<img width="1691" alt="Capture d’écran 2021-03-11 à 23 23 57" src="https://user-images.githubusercontent.com/36271388/110863365-dbece800-82c0-11eb-8ffe-639960c7e917.png">

Well... It isn't much better now. 😅

**Comment by alcover** [comment]
Apparently git does not allow to add an empty dir..
So I put a dummy file in bin/ then added and pushed it... not super elegant.
Merci.
