### ISSUE TITLE
Provide CMakeList for compilation on different platforms

### ISSUE THREAD

**Issue by EwoutH** [alcover/stricks#6]
A `CMakeList.txt` file would be useful to allow reproducible builds on other platforms, like Windows and macOS.

See the [CMake Tutorial](https://cmake.org/cmake/help/latest/guide/tutorial/index.html).

**Comment by alcover** [comment]
I never used cmake. 
I understand one of its advantage is easy cross-platforming,
but for the moment, I'd prefer to keep the project as simple as possible
i.e. Linux + make
