### ISSUE TITLE
CodeBlocks compilation error

### ISSUE THREAD

**Issue by fabek** [alcover/stricks#8]
Hello, 

I've got an error when compiling stx.c in my project. I'm using CodeBlocks v17.12.

`stx.c|47|error: expected declaration specifiers or '...' before '(' token|`

Ps. I'm NOT using c99 or c11 standard. Could you make it comatible please?

![image](https://user-images.githubusercontent.com/9076484/119631940-a90eb680-be10-11eb-9a11-1fa306f1dc6f.png)

**Comment by alcover** [comment]
Hi Fabek,

Sorry but for the moment it will stay C99.
It's still in prototype phase.
